[template]
template-dir = "template_files"

[placeholders]

#将来的に追加するプレースホルダの例、備忘
#blender-file-name = { type = "string", prompt = "What is the name of your Blender file name?", default = "MyBlenderFile" }
#blender-version = { type = "string", prompt = "Blender version (e.g., 4.4)?", default = "4.4" }